from bitalino_thread import btt
import time

btt=btt('20:17:09:18:59:98') # this connects to bitalino

# parameter defaults are:
# btt.batteryThreshold = 30
# btt.acqChannels = [0, 1, 2, 3, 4, 5]
# btt.samplingRate = 1000  # SPS
# btt.nSamples = 100 # samples per readout call. The average is a point in the buffer.
# btt.timeout = 5  # seconds
# btt.fifoDepth = 10  # seconds
# btt.duration = 1000000  # seconds

# info-only parameters
# btt.macAddress
# btt.bitalino  # ref to the object generated by the BITalino class. Can be used to communicate with bitalino

# btt.duration=4 # to run for 4 seconds
btt.acqChannels = [0, 1]
btt.fifoDepth = 2 # seconds

btt.start()

print(btt.btt_fifo.shape)
k=5
while btt.running():
    print(btt.btt_fifo.T) # btt.btt_fifo is a numpy array
    time.sleep(0.5)
    if not k:
        btt.duration=0; # this kills the thread
    k-=1

del btt # stop and disconnect
